### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba-cli#104]
Enter `screen` command. You'll see `Command usage without arguments does not permit. Read help for more information.`
Should be `Command usage without arguments is not permitted. Read help for more information.`

Enter `service` command and specify `Foo`. You'll see `Service name should ends with "Service"`
Should be `Service name should end with "Service"`

**Comment by jreznot** [comment]
It seems that we have changed it in https://github.com/cuba-platform/cuba-cli/issues/99

**Comment by jreznot** [comment]
@alexander-shustanov please check and close if there is no such message anymore
