### ISSUE TITLE
Fix help text

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba-cli#109]
* `entity      Create new entity` -> `entity      Creates new entity`

* Not clear how to execute `screen` commands: 
    ```
    screen      Screen related commands
      Usage: screen [options]       [command] [command options]
        Commands:
          custom      Creates new screen
            Usage: custom [options]

          extend      Extends login and main screens
            Usage: extend [options]

          browse      Creates new browse screen
            Usage: browse [options]

          edit      Creates new edit screen
            Usage: edit [options]
    ```
    Can we add `screen` to usage examples and remove `Usage: screen [options]       [command] [command options]` line?
    For example: 
    ```
          custom      Creates new screen
            Usage: screen custom [options]
    ```

* `service      Create new CUBA service` -> `service      Creates new service`

* `bean      Creates @Component bean` -> `bean      Creates new Spring bean`

* `enumeration      Creates new Enumeration` -> `enumeration      Creates new enumeration`

* `theme      Generates halo theme extension` -> `theme      Generates Halo theme extension`

* `add-component      Installs CUBA platform component -> `add-component      Adds CUBA application component to the project`

* `polymer      Creates empty polymer module` -> `polymer      Creates Polymer module`

* `config      Creates new CUBA config interface` -> `config      Creates new configuration interface`

* `updateScript      Creates new sql update script.` -> `updateScript      Creates new database update script`

* `help      Print help` -> `help      Prints this help`

* `version      Print version` -> `version      Prints CUBA CLI version`

* `cd      Changes current directory, if specified, prints current otherwise` -> `cd      Changes current directory if specified, prints current one otherwise`

**Comment by alexander-shustanov** [comment]
> Can we add screen to usage examples and remove Usage: screen [options] [command] [command options] line?

For now, the help message is completely generated by jcommander, and it is hardly possible to influence on it structure.  I suggest not to change this until Release 1.0.

**Comment by alexander-shustanov** [comment]
Help messages fixed
