### ISSUE TITLE
Is it possible to continue working on project after Cuba-CLI is closed? 

### ISSUE THREAD

**Issue by SpamhaterAlex** [cuba-platform/cuba-cli#135]
Hi, 

I created a sample project with Cuba-CLI and created some entity, screens etc. 
When I closed the CLI, I dont find a way to "reopen" my existing project? 

I suppose this CLI support the developer only when he create the app first time, but when he close it, he can not make any changes on the created project anymore? 

Thanks

**Comment by jreznot** [comment]
Hi, please use forums for questions: https://www.cuba-platform.com/discuss/
