### ISSUE TITLE
Add screens scan to web-spring.xml for CUBA 7.0 projects

### ISSUE THREAD

**Issue by alexander-shustanov** [cuba-platform/cuba-cli#151]
After new screen 7.0 creating the following lines should be added web-spring.xml file:  
`xmlns:gui="http://schemas.haulmont.com/cuba/spring/cuba-gui.xsd"` and 
`<gui:screens base-packages="com.company.projectname.web"/>`

**Comment by jreznot** [comment]
For new project we should include this into web-spring.xml template

**Comment by alexander-shustanov** [comment]
Added the lines to web-sping.xml in project template for 7.0. No migrations added.
