### ISSUE TITLE
Rename all generator commands to `create-`

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#162]
Let's use the same naming convention as popular frameworks:

Grails: http://docs.grails.org/latest/guide/commandLine.html#interactiveMode
Micronaut: https://docs.micronaut.io/latest/guide/index.html

**Comment by alexander-shustanov** [comment]
See new names [here](https://docs.google.com/spreadsheets/d/1GDtap9tS73vUkziWSN3X0vqttwaC-a9pDGr1dTNQBF4/edit#gid=0)
