### ISSUE TITLE
"Parameters" command execution failed

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba-cli#172]
### Environment

- CLI version: 2.0.4
- Operating system: Linux

### Description of the bug or enhancement

- Minimal reproducible example

1. run cli
2. type `parameters` and press "Enter"

![image](https://user-images.githubusercontent.com/6183810/53807144-421f3180-3f68-11e9-8d62-f0360cef8824.png)

**Comment by alexander-shustanov** [comment]
Added clarifying message
