### ISSUE TITLE
Cannot connect to HSQLDB using CLI only

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba-cli#180]
STR:

Create new project using default settings:
1. create-app
2. Use bintray repo
3. Accept default name, namespace, package
4. Use CUBA platform 7.0.3
5. Use HSQLDB as a database
6. After sources are generated, type gradle startDb createDb setupTomcat deploy start in CLI

ER : Application is started

AR: Startup fails:
```
(brave-siren) cuba>gradle startDb createDb setupTomcat deploy start

> Task :app-core:createDb FAILED
Using database URL: jdbc:hsqldb:hsql://localhost/bravesiren, user: sa
Executing SQL: drop schema public cascade;
java.sql.SQLTransientConnectionException: connection exception: connection failure: java.io.EOFException
Using database URL: jdbc:hsqldb:hsql://localhost/bravesiren, user: sa

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app-core:createDb'.
> Unable to get SQL instance
```
I guess we need to upgrade HSQLDB driver version in CLI project generator to 2.4, because after the project is opened in STUDIO, we can run it without any issues

**Comment by DukeKan** [comment]
I have got this error on CUBA CLI 2.1.0 and CUBA Platform 7.1.1 with bintray repository
gradlew startDb shows output:
> Task :app-core:startDb
HSQL is not up in 10 seconds

@alexander-shustanov  @belyaev-andrey  any advices?
