### ISSUE TITLE
let studio respect @DiscriminatorColumn length

### ISSUE THREAD

**Issue by ZuperKeurZ** [cuba-platform/cuba-cli#185]
tested in latest studio (2019.1)

@DiscriminatorColumn(name = "DTYPE", discriminatorType = DiscriminatorType.STRING, length = 64)

length is not respected, the editor keeps referring to a max default of 31

**Comment by jreznot** [comment]
It is not Studio bug tracker, you'd better ask about this on the official forum: https://www.cuba-platform.com/discuss/latest
