### ISSUE TITLE
Plugin interface

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#2]
1. Interface
2. ServiceLoader
3. Extension points:

3a: register interfaces
3b: events?

**Comment by alexander-shustanov** [comment]
Copy paste from kdocs:

To make CUBA CLI able to load your plugin your should add
```
provides com.haulmont.cuba.cli.CliPlugin with `your module class`;
```
to module-info.java.
Lifecycle is served by Guava EventBus. After plugin loading it will be registered in event bus.
To subscribe an event simply add void method with single parameter of the event type and
mark the method with an annotation [com.google.common.eventbus.Subscribe].
Available events are:
* [com.haulmont.cuba.cli.event.InitPluginEvent]
* [com.haulmont.cuba.cli.event.BeforeCommandExecutionEvent]
* [com.haulmont.cuba.cli.event.AfterCommandExecutionEvent]
* [com.haulmont.cuba.cli.event.ModelRegisteredEvent]
* [com.haulmont.cuba.cli.event.DestroyPluginEvent]
* [com.haulmont.cuba.cli.event.FailEvent]
After CLI is launched it fires [InitPluginEvent], and all subscribed plugins may register their commands.
Before CLI is closed it fires [DestroyEvent].
We use [Kodein-DI](http://kodein.org/Kodein-DI/) as a dependency injection container.
All default dependencies are available throw the [com.haulmont.cuba.cli.kodein] instance.
But if you need to provide your own dependencies in your plugin, you can extend default kodein,
and use it inside your plugin.
