### ISSUE TITLE
Project template

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#3]
1. Structure ?
2. Variables ?
3. Files - modules/ configs / etc for 6.8
4. Modules: global, core, web

**Comment by alexander-shustanov** [comment]
Project structure:
.
+--gradle
|&nbsp;&nbsp;&nbsp;+--... //wrapper files
+--modules
|&nbsp;&nbsp;&nbsp;+--global
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+--...
|&nbsp;&nbsp;&nbsp;+--core
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+--...
|&nbsp;&nbsp;&nbsp;+--web
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+--...
+--build.gradle
+--gradlew
+--gradlew.bat
+--settings.gradle


Questions:

1. Project name
1. Project namespace
1. Root package
1. CUBA Platform version
