### ISSUE TITLE
Question: running CLI in single command mode

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/cuba-cli#47]
Hi,

I played around a little with this project. I think it is a great idea and I'm really looking forward where it goes. 

I read the quick start in the wiki: https://github.com/cuba-platform/cuba-cli/wiki/Quick-Start#1-cuba-cli-basics

It says:
> CLI can work in two modes: shell mode and single command mode.

I was just wondering how to run it in the single command mode? I assume you mean something like 
`$ cuba-cli entity --entityName=Customer` instead of going through the Q&A process. Is that right? I was only ably to execute `$ cuba-cli entity` directly, but still get into the Q&A phase afterwards.

Perhaps you can clarify that a little bit for me and in the wiki as well.

Bye
Mario

**Comment by jreznot** [comment]
Hi,
This project is not announced yet and can be dramatically changed. So I cannot not answer your question.

Please wait until we reveal it for the community.

**Comment by mariodavid** [comment]
Well, I am aware (because I looked into the code) at which stage this project is and that nothing is set in stone at this point in time. I was expect to have a conversation regarding what your plans are for that, not how it currently works or how it will work - more from a implementation perspective.

I was actually thinking of doing some PRs depending on if there is anything that can be implemented by an outsider, how the complexity is etc. So, does "Please wait until we reveal it for the community" also mean that you are not interested in code contributions?

If you don't want to answer questions, this is totally fine, but why are you developing it in the open, if this shouldn't be seen by the public?


Bye
Mario

**Comment by jreznot** [comment]
Thank you for your interest. I understand that you want to help us to deliver good open source product.

As usually, we are interested in contributions, but still we have not yet reviewed this functionality internally. It is extremely fresh and even does not have README.

We are planning to change some APIs, commands, usability and approaches. That is why we cannot accept PRs right now.

When it will be announced you will find examples of custom templates, usage demos and plug-in development recipe. As for your question, I believe you will find answer right in the README once it is published.

**Comment by jreznot** [comment]
As we hugely refactor the code every day it wouldn’t make a lot of sense to accept PRs currently, however, we would be happy to see your thoughts under the `type: idea` label
