### ISSUE TITLE
Funny name generator for projects

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#48]
Let's introduce naming algorithm that will generate unique names of projects instead of `untitled`.

Adjectives:

- great
- cool
- ambitious
- generous
- cute
- dear
- nice
- reliable
- solid
- trusty
- simple
- pure
- brave
- manly
- fearless
- artful
- vivid
- utopic
- lucid
- radiant

Animals:

- phoenix
- centaur
- mermaid
- leviathan
- dragon
- pegasus
- siren
- hydra
- sphinx
- unicorn
- wyvern
- behemoth
- griffon
- dodo
- mammoth

**Comment by knstvk** [comment]
👍

**Comment by jreznot** [comment]
Let's use dash (-) symbol instead of underscore

**Comment by jreznot** [comment]
Also, we should always create a new folder for project inside of current with the specified project name.
