### ISSUE TITLE
Dialog system

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#5]
1. Types? 
2. Optional answers?
3. Builder?
4. Parsing from template?

**Comment by alexander-shustanov** [comment]
Available dialog questions:

- Plain question - returns string
- Options question - returns string, that is one of specified options
- Confirmation question (y/n) - returns boolean value
- Question list - returns Map<String, Any>

All questions can have validation rules. All except Question list can have default values, that can be calculated by previous question answers.

Answers may be optional, depending on previous question answers.

Questions may be parsed from static template's template.xml. Only plain and option quesitons are supported.

There is a sort of DSL written on kotlin to construct questions.
