### ISSUE TITLE
Newly created folder with project are located at %HOME% directory on mac os

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba-cli#54]
Reproduces only on mac os.
1) Open CLI
2) Execute create-app

AR: project is placed in %HOME% folder. On win and linux folder with the project are located in cli folder

**Comment by jreznot** [comment]
> On win and linux folder with the project are located in cli folder

It is not OK too.

**Comment by alexander-shustanov** [comment]
Was fixed in #122
