### ISSUE TITLE
There is no delimiter between options and input

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#60]
CLI shows no delimiter, but should insert something like ` : ` or ` > `

![bug-delimeter.png](https://images.zenhubusercontent.com/5ae3309c4b5806bc2bd0e8d8/8c12ee2a-7a94-40bc-8714-f8c95f958bbd)

Another example:
```
cuba>screen

> Screen name screenfearlesssiren$Customer.browse
```

**Comment by alexander-shustanov** [comment]
Added `>` sign
