### ISSUE TITLE
Replace red highlighting of default values with braces or underline it

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#65]
It is not readable in white terminals in Mac OS or from IntelliJ IDEA

![cli-idea.png](https://images.zenhubusercontent.com/5ae3309c4b5806bc2bd0e8d8/d4b4116f-fed3-4532-9389-e68c791b3594)

**Comment by alexander-shustanov** [comment]
Default values surrounded with parentheses
