### ISSUE TITLE
Integration with Gradle

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#66]
Implement ability to build and run application from CLI by delegating execution to Gradle

Check Grails, it supports running gradle build / run from Grails CLI.

It seems, they use Gradle tooling for that.

**Comment by alexander-shustanov** [comment]
Added `gradle` command, that delegates execution to `gradlew` or `gradlew.bat` if the files exist, otherwise show message `Gradle wrapper not found`.

**Comment by jreznot** [comment]
Relates to #156
