### ISSUE TITLE
Autocompletion by the TAB button when changing to a child directory

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba-cli#68]
see https://github.com/cuba-platform/cuba-cli/issues/50
1) create a directory with some name ("myNewCubaCliTestProj")
2) open cuba-cli in the folder
3) "cd .."
4) type "cd myNew", hit Tab (as do most users in such case)

AR: nothing

ER: it would be great to complete users input

**Comment by myatlevEvg** [comment]
Reopen.
At the Windows does not work: autocompletion by tab does not complete folders after first completed folders
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/eb79dedb-c913-4d7c-8bfa-c5721a174862)
