### ISSUE TITLE
Able to create screens and entity listeners for embeddable entities

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba-cli#74]
1) _KeyOne_ is the embeddable entity created to present a composite PK. 
2) Execute 'screen browse' or 'screen edit' 
3) Ececute 'entity-listener'

**AR:** _the entity_ is available the screens may be created for it.

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/d28dc771-2415-4c4b-928a-7f05c14cb2a4)

And entity listeners - too:
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/841b4bc5-e03b-4c71-92c8-e6a1f7192439)

**ER:** Studio does not allow to create screens and entity listeners for embeddable entities
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/959543aa-a198-4894-ae10-1b2f1ed906ec)

**Comment by alexander-shustanov** [comment]
Embeddable entities excluded from options.

**Comment by myatlevEvg** [comment]
Reopen.
1) Create a project
2) Create an Embedded entity
3) Try to create ```entity-listener``` or some ```screen``` (not blank)
AR: ![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/6b4a1215-1efc-4657-b189-86f503b85d9d)
Need to show some informative message about what happened.
