### ISSUE TITLE
CLI life cycle

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#8]
1. Parsing
2. Activation - enable plugins, fire events
3. Action - do work

**Comment by alexander-shustanov** [comment]
1. Plugins loading
2. InitPluginEvent, Commands registration.
3. Parse command name and parameters
4. BeforeCommand event
5. Command execution
6. After command event
7. Goto step 3 if runs in shell mode
8. Plugins destroying
9. Exit
