### ISSUE TITLE
Rework 'install-component' task

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba-cli#80]
*The main problem:*
1) open Studio
2) create app component descriptor
3) launch Run -> Install app component

In Studio it means the project will be installed to mavenLocal().
So in CLI we _should rename the task_.

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/62ead26f-e31d-4494-a520-fa27ef11a489)

*One more problem:*
1) Launch 'install-component'
2) Try to read the example of dependency definition (the blue  text)

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/f3544ec4-f3dd-4e7f-a610-2c448053c086)

**Comment by jreznot** [comment]
Let's name it as `add-component`
