### ISSUE TITLE
Do not allow user to specify too old platform for a new project

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba-cli#87]
In #61 implemented that User can define any platform he wants
1) create-app
2) specify 6.2.2
3) open the project in Studio
AR:
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/1232da11-d67d-47dd-ac2c-f06fd2424ee9)

In seems we should limit possible versions somehow

**Comment by IskandarovRost** [comment]
Cannot create a project on SNAPSHOT versions which are available in public repos
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/ad33a53c-8cee-4968-bc3e-51b1e40012b0)

**Comment by alexander-shustanov** [comment]
fixed
