### ISSUE TITLE
Try to get latest available versions from web site

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#88]
There is a special file that contains released platform versions. Let's try to get it if possible and show latest 6.8 / 6.9 versions instead of built-in. If there is no internet or request failed - fallback to built-in versions.

Do not forget to set reasonable timeout to HTTP requests. Add command line flag to skip this check.

**Comment by alexander-shustanov** [comment]
Versions are started to load on cli start on background. To change file url use `--versionsConfigUrl url` option, to skip `--skipVersionLoading` and `--debug` to see debug info.
