### ISSUE TITLE
The project name in console

### ISSUE THREAD

**Issue by MustelaErminea** [cuba-platform/cuba-cli#91]
At this moment the console looks like:

<img width="65" alt="image" src="https://user-images.githubusercontent.com/22814310/42375876-1ba9a43e-812e-11e8-8d65-232da1656a02.png">

Could you please add a setting for adding the "project name" or the path of project?
Like in "zsh" console?

<img width="489" alt="image" src="https://user-images.githubusercontent.com/22814310/42375998-98cbbd1c-812e-11e8-9338-6dd849101382.png">

For example:

audimex-agile>
or 
Haulmont/audimex/audimex-agile>
or 
cuba "audimex-agile">

**Comment by alexander-shustanov** [comment]
Already fixed at #111
