### ISSUE TITLE
'help' and 'version' could not be called in single-command mode

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba-cli#95]
After changes in #88 (handling of params started from"-") 'version' and 'help' could not be called without running interactive mode.

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/68702ccc-7a8f-46bf-8062-3011e9d600b9)

**Comment by alexander-shustanov** [comment]
Help and version commands are called with `cuba-cli help` and `cuba-cli version`.

**Comment by alexander-shustanov** [comment]
fixed
