### ISSUE TITLE
Incorrect datasource name is generated by `screen edit` command

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba-cli#96]
Incorrect datasource name is generated by `screen edit` command

### Environment

- CLI version: cuba-cli-1.0-SNAPSHOT-windows.zip build #129 (17 Jul 18 17:59) 

### Description of the bug or enhancement

- Create an entity in a project (for example, `Customer`)
- Run `screen edit` with default parameters

### Expected behavior
Entity name in singular:
```
<datasource id="customerDs"
                    . . . />
```
### Actual behavior
Entity name in plural:
```
        <datasource id="customersDs"
                    . . . />
```

**Comment by alexander-shustanov** [comment]
fixed
