### ISSUE TITLE
Unification of TODO style

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba-cli#98]
Up to CLI version `cuba-cli-1.0-SNAPSHOT-windows.zip` build #129 (17 Jul 18 17:59), the TODO stubs are generated with different capitalization:

```
-- todo add your columns here
<!--todo Specify columns here-->
```

**Suggestion:**
Write `TODO` always in capitals, and the following text always in lower case:

```
-- TODO add your columns here
<!--TODO specify columns here-->
```

**Comment by alexander-shustanov** [comment]
Done
