### ISSUE TITLE
Handle `screen` command input without arguments

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba-cli#99]
Handle `screen` input without browse/edit arguments 

### Environment

- CLI version: cuba-cli-1.0-SNAPSHOT-windows.zip build #129 (17 Jul 18 17:59) 

### Description of the bug

- Run `screen` command with default parameters

### Expected behavior

Something like "Input browse/edit" warning

### Actual behavior

An undescriptive exception:

```
cuba>screen

FAILURE: Command execution failed with an exception.

* What went wrong:
> Command usage without arguments does not permit. Read help for more information.

* Try:
Run `stacktrace` command to get full stack trace or use --stacktrace option.

* Visit https://www.cuba-platform.com/discuss/ to get more help.
```
![screenshot_1](https://user-images.githubusercontent.com/11287637/43063931-7f81122e-8e6e-11e8-8534-afec48c409f8.png)

**Comment by jreznot** [comment]
It would be great if we show available commands instead of error
